# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sqrt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sqrt.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsqrt.proto\"\x1d\n\x0bSqrtRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0cSqrtResponse\x12\x10\n\x08num_sqrt\x18\x01 \x01(\x05\x32\x32\n\x0bSqrtService\x12#\n\x04Sqrt\x12\x0c.SqrtRequest\x1a\r.SqrtResponseb\x06proto3'
)




_SQRTREQUEST = _descriptor.Descriptor(
  name='SqrtRequest',
  full_name='SqrtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='SqrtRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=43,
)


_SQRTRESPONSE = _descriptor.Descriptor(
  name='SqrtResponse',
  full_name='SqrtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_sqrt', full_name='SqrtResponse.num_sqrt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['SqrtRequest'] = _SQRTREQUEST
DESCRIPTOR.message_types_by_name['SqrtResponse'] = _SQRTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SqrtRequest = _reflection.GeneratedProtocolMessageType('SqrtRequest', (_message.Message,), {
  'DESCRIPTOR' : _SQRTREQUEST,
  '__module__' : 'sqrt_pb2'
  # @@protoc_insertion_point(class_scope:SqrtRequest)
  })
_sym_db.RegisterMessage(SqrtRequest)

SqrtResponse = _reflection.GeneratedProtocolMessageType('SqrtResponse', (_message.Message,), {
  'DESCRIPTOR' : _SQRTRESPONSE,
  '__module__' : 'sqrt_pb2'
  # @@protoc_insertion_point(class_scope:SqrtResponse)
  })
_sym_db.RegisterMessage(SqrtResponse)



_SQRTSERVICE = _descriptor.ServiceDescriptor(
  name='SqrtService',
  full_name='SqrtService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sqrt',
    full_name='SqrtService.Sqrt',
    index=0,
    containing_service=None,
    input_type=_SQRTREQUEST,
    output_type=_SQRTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SQRTSERVICE)

DESCRIPTOR.services_by_name['SqrtService'] = _SQRTSERVICE

# @@protoc_insertion_point(module_scope)
