# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protobufs/helloworld.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import protobufs.helloworld_pb2


class GreeterBase(abc.ABC):

    @abc.abstractmethod
    async def SayHello(self, stream: 'grpclib.server.Stream[protobufs.helloworld_pb2.HelloRequest, protobufs.helloworld_pb2.HelloResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/Greeter/SayHello': grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobufs.helloworld_pb2.HelloRequest,
                protobufs.helloworld_pb2.HelloResponse,
            ),
        }


class GreeterStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Greeter/SayHello',
            protobufs.helloworld_pb2.HelloRequest,
            protobufs.helloworld_pb2.HelloResponse,
        )
