# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recommendations_pb2 as recommendations__pb2


class RecommendationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recommend = channel.unary_unary(
        '/Recommendations/Recommend',
        request_serializer=recommendations__pb2.RecommendationRequest.SerializeToString,
        response_deserializer=recommendations__pb2.RecommendationResponse.FromString,
        )


class RecommendationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Recommend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommendationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recommend': grpc.unary_unary_rpc_method_handler(
          servicer.Recommend,
          request_deserializer=recommendations__pb2.RecommendationRequest.FromString,
          response_serializer=recommendations__pb2.RecommendationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Recommendations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
